apiVersion: v1
kind: PersistentVolume
metadata:
  name: wemoux-pv
spec:
  capacity:
    storage: 125M
  accessModes:
  - ReadWriteMany
  hostPath:
    path: /srv/wemoux
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wemoux-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 125M
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wemoux-bot
spec:
  selector:
    matchLabels:
      app: wemoux-bot
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wemoux-bot
    spec:
      imagePullSecrets:
      - name: aerum-registry
      containers:
      - image: aerum.co/bots/wemoux
        name: wemoux-bot
        env:
        - name: DISCORD_TOKEN
          valueFrom:
            secretKeyRef:
              name: wemoux-bot-config
              key: DISCORD_TOKEN
        - name: LOG_OF_LAG_ID
          valueFrom:
            secretKeyRef:
              name: wemoux-bot-config
              key: LOG_OF_LAG_ID
        volumeMounts:
        - mountPath: /bot/
          name: config-mount
      volumes:
      - name: config-mount
        persistentVolumeClaim:
          claimName: wemoux-pvc

