name: Deployment

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Git Repository
      uses: actions/checkout@v3
    - name: Build Docker Image
      run: docker build . --file Dockerfile --tag aerum.co/bots/wemoux
    - name: Login to aerum.co
      uses: docker/login-action@v1
      with:
        registry: aerum.co
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push to aerum.co
      run: docker push aerum.co/bots/wemoux
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Authorize Cluster
      uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBECTL_CONFIG }}
    - name: Redeploy Manifest
      uses: actions-hub/kubectl@master
      with:
        args: apply -f $GITHUB_WORKSPACE/kubernetes.yaml
    - name: Restart Deployment
      uses: actions-hub/kubectl@master
      with:
        args: rollout restart deployment/wemoux-bot

