name: Deployment

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Git Repository
      uses: actions/checkout@v3
    - name: Build Docker Image
      run: docker build . --file Dockerfile --tag aerum.co/bots/wemoux
    - name: Login to aerum.co
      uses: docker/login-action@v1
      with:
        registry: aerum.co
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push to aerum.co
      run: docker push aerum.co/bots/wemoux
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Authorize Cluster
      uses: tale/kubectl-action@main
      env:
        base64-kube-config: ${{ secrets.KUBECTL_CONFIG }}
        kubectl-verion: v1.22.4
    - name: Redeploy Manifest
      run: kubectl apply -f $GITHUB_WORKSPACE/kubernetes.yaml
    - name: Restart Deployment
      run: kubectl rollout restart deployment/wemoux-bot

