name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Git Repository
      uses: actions/checkout@v3
    - name: Build Docker Image
      run: docker build . --file Dockerfile --tag aerum.co/bots/wemoux
    - name: Login to aerum.co
      uses: docker/login-action@v1
      with:
        registry: aerum.co
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push to aerum.co
      run: docker push aerum.co/bots/wemoux
    
